name: "test"

on:
  pull_request:
  push:
    branches:
      - "main"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: "Build faucet"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build faucet
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: faucet:test
          cache-from: type=gha
          # github allows only 10GB of cache
          # so save cache only on merge to master
          # to use less space and speed up CI
          cache-to: ${{ github.event == 'push' && 'type=gha,mode=max' || '' }}
